### ISSUE TITLE
not starting due to missing svg

### ISSUE THREAD

**Issue by OriginalBootZ** [flathub/io.github.simple64.simple64#27]
Hi,

Encountered the following error when trying to start flatpak version of Simple64

![2023-01-03_22-44](https://user-images.githubusercontent.com/9661278/210446389-29d12999-6bca-4205-87bc-28dc04ab237c.png)

**Comment by loganmc10** [comment]
That error is unrelated to why the emulator isn't starting.

It's likely that your computer doesn't meet the minimum requirements: https://github.com/simple64/simple64/wiki/simple64-FAQ#1-what-are-the-requirements-for-simple64

**Comment by OriginalBootZ** [comment]
OK Fine! The requirements are NOT described on the install page. My bad not looking at that in the beginning but I assumed as flatpak runs on any Linux the app would be self sustaining (if that is correct English) but it seems not.
I will close it and turn my attention to flathub maintainers then.

**Comment by loganmc10** [comment]
Yeah sorry I'm not sure of a way to make flatpak only install for certain CPU architectures
