### ISSUE TITLE
Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by jonian** [flathub/io.github.simple64.simple64#80]
Hi, the application fails to launch on Arch Linux with GNOME 46 on Wayland with the error below.
 
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, vnc, linuxfb, eglfs, offscreen, minimal, wayland-egl, minimalegl, wayland, vkkhrdisplay.
```

**Comment by waeada** [comment]
Hi, are you using the cv2 module?  If you are using it, it's possible that cv2 is conflicting with pyqt, installing the headless cv2 library can solve this problem.

**Comment by loganmc10** [comment]
This is not a bug specific to simple64, something is wrong with the flatpak Qt setup on your machine, but I don't think it is related to this package

**Comment by jonian** [comment]
Other emulators in Qt like Dolphin, Duck Station and Rosalie's Mupen GUI work without issues. Don't think it is an issue with my setup.

**Comment by loganmc10** [comment]
Are you using the flatpak? Or did you install it from AUR?

**Comment by jonian** [comment]
I'm using the flatpak.
![Screenshot From 2024-10-08 23-05-30](https://github.com/user-attachments/assets/d3d9b15b-1b13-48e4-adad-a1d863900a77)

**Comment by loganmc10** [comment]
You could also try this (this also works for me):

```
QT_QPA_PLATFORM=wayland flatpak run io.github.simple64.simple64
```

But I would think this shouldn't make a difference, since wayland should already be the default

**Comment by jonian** [comment]
Yes I have `QT_QPA_PLATFORM=xcb` in `/etc/environment ` to force X11 on Qt apps. And yes using the command below it works,

```
QT_QPA_PLATFORM=wayland flatpak run io.github.simple64.simple64
```

**Comment by loganmc10** [comment]
I just checked, and both Dolphin and RMG are only exposing X11 support, not Wayland, which is why you don't have issues with those emulators, but you'll probably have issues with any Qt application that is configured to use Wayland (as a flatpak).

**Comment by jonian** [comment]
You are answering my question as I write them :smile:. Thanks for the solution!
